global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
- job_name: aggregator 
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http 
  follow_redirects: true
  static_configs:
  - targets:
      - 172.17.0.1:8080
  
  

#port 9090